### ISSUE TITLE
Replacing shared_ptr<cv::Mat> with cv:Mat 

### ISSUE THREAD

**Issue by chrberger** [chalmers-revere/opendlv#18]
Instead of using a shared_ptrcv:Mat, a regular class member cv::Mat m_image; is sufficient:
- http://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html#videocapture-read
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/core/proxy/include/camera/opencvdevice.hpp#L52
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/core/proxy/src/camera/opencvdevice.cpp#L48
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/core/proxy/src/camera/opencvdevice.cpp#L92
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/core/proxy/src/camera/opencvdevice.cpp#L103-L104

**Comment by olbender** [comment]
Fixed by camera patch.
