### ISSUE TITLE
Transform V2vInbound to separate data fields

### ISSUE THREAD

**Issue by chrberger** [chalmers-revere/opendlv#21]
As discussed today, it could make sense to directly extract the data fields from the string here to allow direct visualization in odcockpit for example:
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/core/proxy/src/v2v/v2v.cpp#L85
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/knowledge/include/gcdc16/v2viclcm/v2viclcm.hpp#L54-L83

**Comment by bjornborg** [comment]
This will be taken into consideration when refactoring and revising the v2x modules.
