### ISSUE TITLE
Suggestion: use CSVFromVisitableVisitor to create .csv file

### ISSUE THREAD

**Issue by chrberger** [chalmers-revere/opendlv#22]
Once the V2v-data is available as messages in the .odvd file, we can use the CSVFromVisitableVisitor to transform the fields from a concrete message into a CSV file:

Examples:
- https://github.com/se-research/OpenDaVINCI/blob/master/libopendavinci/testsuites/CSVFromVisitableVisitorTestSuite.h#L187-L190
- https://github.com/bellonemauro/opendlv/blob/master/code/system/application/sensation/src/sensation.cpp#L132 + https://github.com/bellonemauro/opendlv/blob/master/code/system/application/sensation/src/sensation.cpp#L137-L142 + https://github.com/bellonemauro/opendlv/blob/master/code/system/application/sensation/src/sensation.cpp#L181

Replacing:
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/knowledge/src/gcdc16/v2viclcm/v2viclcm.cpp#L161-L192
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/knowledge/src/gcdc16/v2viclcm/v2viclcm.cpp#L161-L192
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/knowledge/include/linguistics/v2vcam/buffer.hpp
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/knowledge/include/linguistics/v2vcam/buffer.hpp

Potentially here as well? Checking with @olbender 
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/sensation/src/audition/audition.cpp#L83-L106

Remove:
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/knowledge/src/linguistics/v2vcam/buffer.cpp
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/knowledge/include/linguistics/v2vcam/buffer.hpp

**Comment by chrberger** [comment]
Default values can be specified in the .odvd file like this:
- https://github.com/se-research/OpenDaVINCI/blob/master/odDataStructureGenerator/org.opendavinci.datamodel/test/odvd/Test12.odvd#L14
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/knowledge/include/linguistics/v2vcam/buffer.hpp

Replacing:
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/knowledge/include/gcdc16/v2viclcm/v2viclcm.hpp#L54-L83

**Comment by bjornborg** [comment]
The v2x modules will be migrated to opendlv.core and furthermore the recorded data will be stored using protobuf.
