### ISSUE TITLE
Suggestion: use Eigen3 shipped with OpenDaVINCI to simplify code 

### ISSUE THREAD

**Issue by chrberger** [chalmers-revere/opendlv#23]
Adjust the include header here:
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/perception/include/detectlane/DecisionMaking.h#L4
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/perception/include/detectlane/Drawing.h#L4
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/perception/include/detectlane/ExtractingRegions.h#L4
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/perception/include/detectlane/ProcessImage.h#L4

Similar to:
- https://github.com/bellonemauro/opendlv/blob/master/code/system/libs/EKF/include/Matrix.hpp#L27

**Comment by bjornborg** [comment]
Eigen3 is currently implemented and used in those modules.
