### ISSUE TITLE
Separation declaration from definition + transform to class

### ISSUE THREAD

**Issue by chrberger** [chalmers-revere/opendlv#24]
Adjust implementation:
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/perception/include/detectlane/DecisionMaking.h
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/perception/include/detectlane/Drawing.h
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/perception/include/detectlane/ExtractingRegions.h
- https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/perception/include/detectlane/ProcessImage.h

**Comment by olbender** [comment]
Outdated.
