### ISSUE TITLE
Fix missing return in detectlane

### ISSUE THREAD

**Issue by chrberger** [chalmers-revere/opendlv#26]
The commented return here: https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/perception/src/detectlane/detectlane.cpp#L75 will make this method fail if the Container is of the wrong type:

https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/perception/src/detectlane/detectlane.cpp#L82-L83

**Comment by olbender** [comment]
Fixed.
