### ISSUE TITLE
Fix missing return in detectvehicle

### ISSUE THREAD

**Issue by chrberger** [chalmers-revere/opendlv#31]
The commented return here: https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/perception/src/detectvehicle/detectvehicle.cpp#L80 will make this method fail if the Container is of the wrong type:

https://github.com/chalmers-revere/opendlv/blob/experiment.idiada/code/system/application/perception/src/detectvehicle/detectvehicle.cpp#L90-L91

**Comment by olbender** [comment]
Fixed.
