### ISSUE TITLE
Adjusting the scope of variables in DetectLane

### ISSUE THREAD

**Issue by chrberger** [chalmers-revere/opendlv#32]
[application/perception/src/detectlane/detectlane.cpp:177]: (style) The scope of the variable 'laneOffset' can be reduced.
[application/perception/src/detectlane/detectlane.cpp:180]: (style) The scope of the variable 'p1' can be reduced.
[application/perception/src/detectlane/detectlane.cpp:180]: (style) The scope of the variable 'p2' can be reduced.

**Comment by olbender** [comment]
Outdated.
