### ISSUE TITLE
Setting width and height of camera stream (cv::VideoCapture) does nothing

### ISSUE THREAD

**Issue by Plankton555** [chalmers-revere/opendlv#33]
In the proxy-camera (opencvdevice.cpp), the width and height properties of the cv::VideoCapture are set. However, the change does never seem to be applied. The following code

```
if (m_capture->isOpened()) {
  std::cout << "Open. width: " << a_width << " height: " << a_height << std::endl;
  m_capture->set(CV_CAP_PROP_FRAME_WIDTH, a_width);
  m_capture->set(CV_CAP_PROP_FRAME_HEIGHT, a_height);
  std::cout << "After. width: " << m_capture->get(CV_CAP_PROP_FRAME_WIDTH) << " height: " << m_capture->get(CV_CAP_PROP_FRAME_HEIGHT) << std::endl;
}
```

may for example result in the output

```
Open. width: 800 height: 600
After. width: 1280 height: 720
```

In the case above, the image read from the cv::VideoCapture was stored in a shared image of a different size. This caused the image, when it was unpacked from the shared image, to be corrupt/wrong.

This happened on a machine running Ubuntu 14.04 LTS.

After a short discussion with @chrberger, the problem might be caused by incorrect OpenCV/v4l on the machine?

**Comment by chrberger** [comment]
The suggestion would be to

(a) check whether the requested size is supported by the OpenCV/v4l setup
and
(b) either resize the image (scale down) to meet the requested size
or
(c) warn about the non matching WxH and use the one from the OpenCV framework.

@olbender: What is your take?

**Comment by bjornborg** [comment]
Is this problem still persisting or relevant?

**Comment by Plankton555** [comment]
I do not remember if it was solved or not.

**Comment by bjornborg** [comment]
I'll close it for now then.
