### ISSUE TITLE
FindodDataStructureGenerator

### ISSUE THREAD

**Issue by bellonemauro** [chalmers-revere/opendlv#5]
Hello, 
this variable was not automatically found in cmake:

CMake Error at CMakeLists.txt:63 (include):
  include could not find load file:

```
FindodDataStructureGenerator
```

Mauro

**Comment by bjornborg** [comment]
This could be resolved by adding -D ODDATASTRUCTUREGENERATOR_PATH=/opt/od3/bin/ to the cmake command.
