### ISSUE TITLE
DataSpy and TruckReplay needs further review

### ISSUE THREAD

**Issue by olbender** [chalmers-revere/opendlv#56]
The tools DataSpy and TruckReplay need further review:
- What are the long term needs?
- Adjust to make compliant with OpenDLV.

**Comment by bellonemauro** [comment]
Long term needs of the dataspy is to have a tool that checks what messages go through the odsupercomponent.
Whereas, the truckreplay is actually a sensor message simulator, and in my opinion it helps a lot the development when you are not on the truck. Most of the times you don't have the hardware, or you prefer to simulate messages as it is expensive to be always on the truck. Moreover, even though we have always the truck, our team is composed of several persons and if one is running a test, the others can still do their own development simulating sensors.

M.
