### ISSUE TITLE
Duplicated code in DetectLane and DetectVehicle

### ISSUE THREAD

**Issue by Plankton555** [chalmers-revere/opendlv#77]
Some functions for transforming point coordinates using transformation matrices are directly copied from DetectLane to DetectVehicle. Should be fixed in the future.

Known examples are:
ReadMatrix()
TransformPointToGlobalFrame()

**Comment by bjornborg** [comment]
Perhaps we should create and design a passive module that will listen requests of transforms, e.g. modules sending pixels arguments (with specified camera name) to the passive module and will compute the transformation and send it back to the module who made that request.

**Comment by olbender** [comment]
@bjornborg @chrberger , This is an old, but still very good idea. Do we still have the need for it? We should to minimize all our microservices. How is the progress on detect-vehicle?

**Comment by bjornborg** [comment]
Detect-vehicle is still under review.
